<?php

/**
  * Zoom
  *
  * Ninimal but powerful web application framework for PHP
  *
  * This content is not open source but application built with zoom can be modified by users, but not to be sold
  *
  * Copyright (c) 2018, Zoom Inc, ZumClouds Nigeria.
  *
 **/

/**
 * --------------------------------- DO NOT EDIT THIS FILE ---------------------------------
 */

/**
 * Zoom Version
 *
 * @var string
 *
 */

const ZOOM_VERSION = '1.1.0';

defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Config file should be required first
 */

if (file_exists(BASEPATH.'/core/config.php')) {

  require BASEPATH.'/core/config.php';

  /**
  *Define Config file path
  **/

  define('CONFIG', APPATH.'/config/config.php');

}

else{

  die('An important script is missing!, Re-install Zoom');

}

if (file_exists(BASEPATH.'/core/CommonFunctions.php')) {

  require BASEPATH.'/core/CommonFunctions.php';

}
else{

   die('Could not Locate a system file... Please check your appsys configuration in '.INDEX);

}

// Load Zoom Config file

$zoom = new zoom_config();